### ISSUE TITLE
adb: unknown host service

### ISSUE THREAD

**Issue by gMan1990** [voodik/puttyadb#1]
<img width="657" alt="WX20200515-163850@2x" src="https://user-images.githubusercontent.com/5050994/82030173-a55b3680-96ca-11ea-8a6d-ee2b0e94de12.png">
<img width="605" alt="WX20200515-163913@2x" src="https://user-images.githubusercontent.com/5050994/82030187-a9875400-96ca-11ea-8126-a21bbb556580.png">

**Comment by voodik** [comment]
![PuTTY Configuration 5_16_2020 02_41_06](https://user-images.githubusercontent.com/6307166/82085003-e5e49f80-971e-11ea-9081-6b5406872502.png)
![PuTTY Configuration 5_16_2020 02_41_29](https://user-images.githubusercontent.com/6307166/82085042-f432bb80-971e-11ea-967d-1885a529c103.png)
